### ISSUE TITLE
Missing tool

### ISSUE THREAD

**Issue by TreetopInnovation** [jbramwell/VSTS-Tools#1]
I just installed this interesting tool on my TFS on prem.
However, the result was the only the modules List Files and List Variables appeared as tools to choose.
![capture1](https://cloud.githubusercontent.com/assets/4697155/15504997/d1fe1b8a-21c1-11e6-92ed-1f528e0c4e91.PNG)

The interestings one and main reason for download, Keep, were nowhere to find.
Am I missing anything?
Many thanks in advance! /Hakan

**Comment by jbramwell** [comment]
@TreetopInnovation Are you using hosted build (on VSTS) or running your build agents on-premises? Some of the build tasks in this extension requires the build agents to be version 1.99 or greater. If you're using build agents on-premises (or your own build agents hosted in Azure/AWS) what is the version of the agent(s) in use?

**Comment by TreetopInnovation** [comment]
We are running TFS on prem with build servers also on prem.
TFS 2015 update 2.1 with agents running version 1.95.1.
These are the agents that are distributed through my TFS.
Do you know where to find the 1.99 version Agents and if they can run on prem?
Thanks for a good service!

**Comment by jbramwell** [comment]
@TreetopInnovation Currently, the build agents for TFS on-premises are updated via the quarterly updates. When the next quarterly update comes out (and you've applied it) the missing build tasks should show up and be usable.

That said, there are a couple of things I still yet need to do before closing this out:

1. I need to update the VSTS-Tools docs to clearly state which build tasks are available on which platform (e.g. VSTS vs. TFS 2015 w/Update 1, 2, etc.).
2. I need to follow up with Microsoft to see if the API change I am relying on for the VSTS Keep task is available in TFS 2015 Update 2.1. If it is, then I can lower the version requirement so the task will show up.

I'll follow back up once I have taken care of the two items above.

**Comment by TreetopInnovation** [comment]
OK. Thanks for the information.
Please let me know if there is anything I can do to help.
All the best/Håkan

**Comment by jbramwell** [comment]
FYI... just so you don't think I've forgotten about this, I've been e-mailing back and forth with a few folks at Microsoft over the past few days trying to figure out why some of the tasks don't get installed on TFS (when they do on VSTS). Once we get that resolved, I'll follow back up again with the resolution.

**Comment by TreetopInnovation** [comment]
Hi Jeff,
Thanks for your energy and commitment!
You have some really useful tools and we will be glad to use them, whenever it is possible.
All the best /Hakan

**Comment by jbramwell** [comment]
OK. I *think* the issue has now been resolved. If you uninstall and re-install the latest version (1.3.1) you should see four of the five tasks show up in TFS. Currently, the VSTS-Tools Keep task will not show up because TFS 2015 QU2.1 does not have the correct API. I am hoping the next update will.

Please let me know if it's working for you. Thanks!

**Comment by jbramwell** [comment]
It's been nearly three weeks since I last heard anything on this issue. Based on my testing, and feedback from others, I am assuming this issue is resolved at this time. If you run into any further issues please do not hesitate to contact me. Thanks!
