### ISSUE TITLE
Deprecated task execution handler

### ISSUE THREAD

**Issue by Thilas** [jbramwell/VSTS-Tools#12]
I recently started to get this sort of warnings when running your tasks:
```
##[warning]Task 'VSTSToolsListVariables' (1.4.2) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
```

Could you please have a look? Or if you prefer, I can give it a try and submit a pull request.

Thanks.

**Comment by Thilas** [comment]
Any news about this? The warnings are really annoying... and as I said I can submit a PR. I just want to make sure first that's ok with you.

FYI, here are the kind of changes that are required: https://github.com/cake-build/cake-vso/pull/49/files

**Comment by Thilas** [comment]
Still nothing? I will most likely fork your extension then.

**Comment by jbramwell** [comment]
Sorry for the late response. Unfortunately, I let it slip by :-\   I can likely give this a look this weekend and see if I can get it updated. However, I am not opposed to pull requests if it's something you'd be interested in taking a look at as well. :-)

**Comment by Thilas** [comment]
Thank you for coming back to me! I can definitely have a closer look and submit a PR. I'll let you know.

**Comment by Thilas** [comment]
As I mentioned in a previous message, fixing those warning messages is fairly easy. I had a quick look at the source code of the extension and unfortunately I can't manage to understand where are the powershell scripts I should be fixing. For instance, in `VSTSToolsListApps` task, its ps1 script should be located at `/VSTS-Extensions/VSTSToolsListApps/listapps.ps1`. But there is no such file in the git repository.

If I look at the latest published vsix file, I can find the expected ps1 files at the expected locations... as well as related js files that doesn't seem to be called at all (BTW they seems to be coming straight from a tutorial) since all tasks are powershell-based, not node-based. And in `/VSTS-Tools.sln`, I can also see the expected ps1 files as well as those js counterparts.

Could you please give me some information about how all this should work?

**Comment by Thilas** [comment]
Looking at the git history, I noticed a previous commit that removed old the ps1 (and js) files. I can't say if this is a mistake or not. In the meantime, I reverted this on my PR at least to show you the kind of changes that was required here. Let me know what you think. Thanks.
