### ISSUE TITLE
Can't see VSTS-* Tasks

### ISSUE THREAD

**Issue by darshanrampatel** [jbramwell/VSTS-Tools#3]
HI,

I can't see any of the VSTS-* tasks in the Add tasks section of my build definition.

![image](https://cloud.githubusercontent.com/assets/14162899/15901289/9da9aaf4-2d9a-11e6-93ed-293cb72f6c0c.png)

I am using VSTS - what do I need to do to see this option? I have enabled the **Allow Scripts to Access OAuth Token.** option.

Thanks.

**Comment by jbramwell** [comment]
@darshanrampatel I just tried uninstalling and re-installing the VSTS-Tools extensions on two separate VSTS accounts and they are showing up in both cases. That said, there are a couple of things you can check:

1. Try uninstalling/re-installing the extensions again (just in case something went "wonky" the first time around :-)). In the ALL tab of the Add Task dialog you will (should) find the tasks between the Visual Studio Test Agent Deployment task and the Windows Machine File Copy task as shown in the screenshot below (your task list could be slightly different depending on what you've installed).

![vsts-tools-tasks](https://cloud.githubusercontent.com/assets/1194460/15914928/9fd4a5ee-2daa-11e6-9aaa-20f22f3ffd3a.png)

2. With the exception of the VSTS-Tools Keep task the VSTS-Tools tasks require the build agent version to be 1.89.0 or greater. The VSTS-Tools Keep task requires the build agent to be version 1.99.0 or greater. You can see what version your build agent is by looking at the agent capabilities as shown in the screenshot below:

![vsts-tools-agent-version](https://cloud.githubusercontent.com/assets/1194460/15915161/940b2c7c-2dac-11e6-83f6-1f6894ce51cf.png)

If your agent versions are less than what is required, I recommend you try updating to the latest version. Generally, this happens automatically so it's likely you're already at the latest version. If not, you can update from the same screen as above like shown in the screenshot below:

![vsts-tools-update-agents](https://cloud.githubusercontent.com/assets/1194460/15915288/bfcf2e02-2dad-11e6-93d5-afa47bade50a.png)

Let me know how this goes and if they're still not showing up, we'll go from there :-)

**Comment by darshanrampatel** [comment]
@jbramwell, thanks - uninstalling and re-installing the extension worked!
